using System;
using UnityEngine;

public class RecogerBala : MonoBehaviour
{
    public Transform puntoMira; // Punto donde se ancla la bala (hijo de la c치mara)
    private GameObject balaSujeta;

    //  Objeto que desaparecer치 al recoger la bala
    public GameObject objetoADesaparecer;

    // Nuevo: Objeto que aparecer치 al recoger la bala
    public GameObject objetoAparecer;

    void Update()
    {
        if (balaSujeta != null)
        {
            balaSujeta.transform.position = puntoMira.position;
            balaSujeta.transform.rotation = puntoMira.rotation;
        }
    }

    public void OnPointerClickXR()
    {
        if (balaSujeta == null)
        {
            Recoger();
        }
    }

    private void Recoger()
    {
        balaSujeta = gameObject;

        // 游댳 Si hay un objeto asignado, lo desactivamos
        if (objetoADesaparecer != null)
        {
            objetoADesaparecer.SetActive(false);
        }

        // 游댳 Si hay un objeto para aparecer, lo activamos
        if (objetoAparecer != null)
        {
            objetoAparecer.SetActive(true);
        }
    }

    private void OnTriggerEnter(Collider otro)
    {
        Debug.Log("Si colisiona");
        if (otro.CompareTag("Ca침on"))
        {
            otro.GetComponent<BaseObjtosInreactuables>().CargarCa침on();
            DesaparecerBala();
        }
    }

    private void DesaparecerBala()
    {
        if (balaSujeta != null)
        {
            balaSujeta = null;
            gameObject.SetActive(false);

            // 游댳 Al desaparecer la bala, ocultamos el objeto que hab칤a aparecido
            if (objetoAparecer != null)
            {
                objetoAparecer.SetActive(false);
            }
        }
    }
}
